# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GenMatVisModelName.ui',
# licensing of 'GenMatVisModelName.ui' applies.
#
# Created: Wed Mar 13 11:32:13 2024
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(454, 211)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setEnabled(True)
        self.checkBox.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.matPrefixLineEdit = QtWidgets.QLineEdit(Form)
        self.matPrefixLineEdit.setObjectName("matPrefixLineEdit")
        self.verticalLayout_5.addWidget(self.matPrefixLineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.sgPrefixLineEdit = QtWidgets.QLineEdit(Form)
        self.sgPrefixLineEdit.setObjectName("sgPrefixLineEdit")
        self.verticalLayout_6.addWidget(self.sgPrefixLineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMargin(0)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.matSuffixLineEdit = QtWidgets.QLineEdit(Form)
        self.matSuffixLineEdit.setObjectName("matSuffixLineEdit")
        self.verticalLayout_3.addWidget(self.matSuffixLineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.sgSuffixLineEdit = QtWidgets.QLineEdit(Form)
        self.sgSuffixLineEdit.setObjectName("sgSuffixLineEdit")
        self.verticalLayout_4.addWidget(self.sgSuffixLineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 5)
        self.horizontalLayout_2.setStretch(2, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.applyBtn = QtWidgets.QPushButton(Form)
        self.applyBtn.setObjectName("applyBtn")
        self.verticalLayout.addWidget(self.applyBtn)
        self.applyToSelBtn = QtWidgets.QPushButton(Form)
        self.applyToSelBtn.setEnabled(True)
        self.applyToSelBtn.setObjectName("applyToSelBtn")
        self.verticalLayout.addWidget(self.applyToSelBtn)
        self.saveSetingBtn = QtWidgets.QPushButton(Form)
        self.saveSetingBtn.setObjectName("saveSetingBtn")
        self.verticalLayout.addWidget(self.saveSetingBtn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label_2.setBuddy(self.label_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "材质球命名", None, -1))
        self.checkBox.setText(QtWidgets.QApplication.translate("Form", "Enable", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form", "规则:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "材质球前缀", None, -1))
        self.matPrefixLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("Form", "前缀", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Form", "SG节点前缀", None, -1))
        self.sgPrefixLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("Form", "前缀", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form", "-模型名称-", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "材质球后缀", None, -1))
        self.matSuffixLineEdit.setText(QtWidgets.QApplication.translate("Form", "_M", None, -1))
        self.matSuffixLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("Form", "后缀", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "SG节点后缀", None, -1))
        self.sgSuffixLineEdit.setText(QtWidgets.QApplication.translate("Form", "_Inst", None, -1))
        self.sgSuffixLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("Form", "后缀", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form", "材质球类型:", None, -1))
        self.comboBox.setProperty("placeholderText", QtWidgets.QApplication.translate("Form", "材质球类型", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "blinn", None, -1))
        self.applyBtn.setText(QtWidgets.QApplication.translate("Form", "执行操作", None, -1))
        self.applyToSelBtn.setText(QtWidgets.QApplication.translate("Form", "应用到选择", None, -1))
        self.saveSetingBtn.setText(QtWidgets.QApplication.translate("Form", "保存设置", None, -1))

